;TRABALHO REALIZADO POR:
;	JOÃO ALMAS N: 2021
;	TOMÁS FARIA RAMOS N: 2022140175
;TAC

.8086
.MODEL SMALL
.STACK 2048

DADOS SEGMENT PARA 'DATA'

	;//////////////////////////RELACIONADO COM O JOGO/////////////////////////;
	
	BOARD_9X9 DB 9 DUP(9 DUP(' '))	    ;BOARD 9X9 INICIALIZADA COM ' '   		
	BOARD_3X3 DB 3 DUP(3 DUP(' '))		;BOARD 3X3 INICIALIZADA COM ' ' 
	JOGADOR1_CHAR DB ?					;CARACTER DO JOGADOR 1
	JOGADOR1_NOME DB 20, 0, 18 DUP('$') ;NOME DO JOGADOR 1
	JOGADOR2_CHAR DB ?					;CARACTER DO JOGADOR 2
	JOGADOR2_NOME DB 20, 0, 18 DUP('$')	;NOME DO JOGADOR 1
	JOGADOR_CURR_CHAR DB ?				;CHAR DO JOGADOR ATUAL
	POS_Y DB 18 						;POS Y PARA GOTO_XY
	POS_X DB 40							;POS Y PARA GOTO_XY
	CHAR DB 32							;GUARDA UM CARACTER
	BOARD_OFFSET_JOGADA DW ?			;INICIO DA BOARD DA ULTIMA JOGADA
	IDX_CURR_X DB ?						;GUARDA O X DA ULTIMA JOGADA FEITA
	IDX_CURR_Y DB ?						;GUARDA O Y DA ULTIMA JOGADA FEITA
	
	;////////////////////////RELACIONADO COM FICHEIROS////////////////////////;
	
	JOGADOR1_PROMPT DB 'Nome do jogador 1: $'
	JOGADOR2_PROMPT DB 'Nome do jogador 2: $'
	JOGADOR_GANHOU_MESSG DB 'Parabens, $'
	VOLTA_PARA_MENU_MESSG DB 'Clique em qualquer tecla para voltar ao menu$'
	
	;////////////////////////RELACIONADO COM FICHEIROS////////////////////////;
	
	ERRO_OPEN DB 'Erro ao tentar abrir o ficheiro$'
	ERRO_LER_MSG DB 'Erro ao tentar ler do ficheiro$'
	ERRO_CLOSE DB 'Erro ao tentar fechar o ficheiro$'
	MENU_FICH DB 'menu.txt', 0
	BOARD_FICH DB 'board.txt', 0
	HANDLE_FICH DW 0
	CAR_FICH DB ?
	
DADOS ENDS

CODIGO SEGMENT PARA 'CODE'
	ASSUME CS:CODIGO, DS:DADOS
	
;////////////////////////////////////MACROS///////////////////////////////////;

GOTO_XY	MACRO POS_X, POS_Y				;DEFINIÇÃO DA MACRO
	MOV	DL, POS_X						;CARREGA VALOR DE POS_X PARA DL
	MOV	DH, POS_Y						;CARREGA VALOR DE POS_Y PARA DH
	CALL SET_CURSOR_POS					;METE O CURSOR NA POSIÇÃO
ENDM									;FIM DA MACRO
	
;////////////////////////////////////CODIGO///////////////////////////////////;

MAIN:
	MOV AX, DADOS						;CARREGA VALOR DE DADOS EM AX
	MOV DS, AX							;CONFIGURA O SEGMENTO DE DADOS COM AX

MOSTRA_MENU:
	MOV POS_X, 40						;DEFINE A POSIÇÃO X DO MENU COMO 40
	MOV POS_Y, 18						;DEFINE A POSIÇÃO Y DO MENU COMO 18
	GOTO_XY POS_X, POS_Y				;POSICIONA O CURSOR EM 40, 18
	CALL APAGA_ECRAN					;APAGA O ECRAN
	LEA DX, MENU_FICH					;CARREGA ENDEREÇO DE MENU_FICH PARA DX		   
	CALL PRINT_FICHEIRO					;FAZ PRINT DO MENU
	CALL INICIALIZA_JOGO				;LIMPA AS BOARDS E OS NOMES

	CALL MOVER_MENU 					;DEIXA MOVER NO MENU
	CMP	DH, 18							;SE Y = 18
	JE PVP								;Salta para PVP
	CMP DH, 20							;SE Y = 20
	JE PVC                              ;Salta para PVc
	CALL EXIT			                ;Salta para EXIT

PVP:									;PLAYER VS PLAYER
	CALL APAGA_ECRAN					;APAGA ECRAN
	GOTO_XY 1, 1						;VAI PARA 1, 1
	LEA DX, JOGADOR1_PROMPT				;STRING A PEDIR PARA INTRODUZIR O NOME
	CALL PRINT_STRING					;DO JOGADOR 1
	LEA DX, JOGADOR1_NOME				;CARREGA O ENDEREÇO DE JODADOR1_NOME 
	CALL GET_STRING						;E PREENCHE O BUFFER COM INPUT
	CALL APAGA_ECRAN					;APAGA ECRAN
	GOTO_XY 1, 1						;VAI PARA 1, 1
	LEA DX, JOGADOR2_PROMPT				;STRING A PEDIR PARA INTRODUZIR O NOME
	CALL PRINT_STRING                   ;DO JOGADOR 2
	LEA DX, JOGADOR2_NOME				;CARREGA O ENDEREÇO DE JODADOR2_NOME 
	CALL GET_STRING                     ;E PREENCHE O BUFFER COM INPUT
	CALL SELECIONA_PRIMEIRO_JOGADOR		;DEFINE OS CARCATERES DOS JOGADORES
	CALL APAGA_ECRAN					;APAGA ECRAN
	LEA DX, BOARD_FICH					;CARREGA O ENDEREÇO DE BOARD_FICH
	CALL PRINT_FICHEIRO					;PRINT DA BOARD
	GOTO_XY 65, 2						;VAI PARA 65, 2
	MOV DL, JOGADOR1_CHAR				;CARREGA DL COM O CHAR DO JOGADOR 1
	CALL PRINT_CHAR						;E MOSTRA NA TELA
	MOV DL, '-'							;CARREGA DL COM -
	CALL PRINT_CHAR                     ;E MOSTRA NA TELA
	LEA DX, JOGADOR1_NOME + 2			;CARREGA DX COM O NOME DO JOGADOR 1
	CALL PRINT_STRING					;E MOSTRA NA TELA (+2 DO BUFFER)
	GOTO_XY 65, 3						;VAI PARA 65, 3
	MOV DL, JOGADOR2_CHAR				;CARREGA DL COM O CHAR DO JOGADOR 2
	CALL PRINT_CHAR                     ;E MOSTRA NA TELA
	MOV DL, '-'                         ;CARREGA DL COM -
	CALL PRINT_CHAR                     ;E MOSTRA NA TELA
	LEA DX, JOGADOR2_NOME + 2           ;CARREGA DX COM O NOME DO JOGADOR 2
	CALL PRINT_STRING	                ;E MOSTRA NA TELA (+2 DO BUFFER)
	
;/////JOGO/////;

PVP_CICLO:
	CALL ATUALIZA_JOGADOR				;MOSTRA O CHAR DO JOGADOR ATUAL
	CALL MOVER							;DEIXA MOVER PELA BOARD
	CALL VERIFICA_VENCEDOR_9X9			;VERIFICA SE CHAR ATUAL GANHOU BOARD
	CALL VERIFICA_VENCEDOR_3X3			;VERIFICA SE JOGADOR ATUAL GANHOU
	CMP AL, 1							;1 SE JOGO GANHO
	JE VENCEDOR							;SALTA PARA VENCEDOR
	CALL MUDA_JOGADOR					;SENÃO, MUDA CHAR ATUAL
	JMP PVP_CICLO						;SE NINGUEM GANHOU CONTINUA O JOGO
	
PVC:
	CALL SELECIONA_PRIMEIRO_JOGADOR

VENCEDOR:								
	GOTO_XY 32, 3						;VAI PARA 32, 3
	LEA DX, JOGADOR_GANHOU_MESSG		;CARREGA O ENDEREÇO DA MENSAGEM
	CALL PRINT_STRING					;MOSTRA A MENSAGEM
	MOV AL, JOGADOR_CURR_CHAR			;MOVE CHAR DO VENCEDOR PARA AL
	CMP AL, JOGADOR1_CHAR				;COMPARA COM JOGADOR 1
	JNE VENCEDOR2						;SE NAO FOR, VENCEDOR É O JOGADOR 2
	GOTO_XY 42, 3						;VAI PARA 42, 3
	LEA DX, JOGADOR1_NOME + 2			;CARREGA ENDEREÇO DO NOME DO JOGADOR 1
	CALL PRINT_STRING					;MOSTRA O NOME DO JOGADOR 1
	JMP VENCEDOR_SAIR					;VAI PARA VENCEDOR_SAIR
	
VENCEDOR2:
	GOTO_XY 42, 3						;VAI PARA 42, 3
	LEA DX, JOGADOR2_NOME + 2           ;CARREGA ENDEREÇO DO NOME DO JOGADOR 2
	CALL PRINT_STRING                   ;MOSTRA O NOME DO JOGADOR 2
	JMP VENCEDOR_SAIR                   ;VAI PARA VENCEDOR_SAIR

VENCEDOR_SAIR:
	GOTO_XY 20, 4						;VAI PARA 20, 4
	LEA DX, VOLTA_PARA_MENU_MESSG		;CARREGA O ENDEREÇO DA MENSAGEM
	CALL PRINT_STRING					;MOSTRA A MENSAGEM
	CALL GET_CHAR						;ESPERA POR UM CARACTER
	JMP MOSTRA_MENU						;VOLTA PARA O MENU
	
;////////////////////////////////PROCEDIMENTOS////////////////////////////////;


SELECIONA_PRIMEIRO_JOGADOR PROC
	MOV BYTE PTR [JOGADOR_CURR_CHAR], 'X'    ;Define o jogador atual como 'X'      
	CALL READ_SYSTEM_TIMER								
	MOV AL, DL						    ;Move parte do tempo atual para AL
	AND AL, 1						    ;Vai dar ou 1 ou 0
	CMP AL, 0								
	JE JOGADOR_X						;Caso o resultado for 0
	JMP JOGADOR_O						;Caso o resultado for 1

JOGADOR_X:
	MOV BYTE PTR [JOGADOR1_CHAR], 'X'	;Define o jogador 1 como X
	MOV BYTE PTR [JOGADOR2_CHAR], 'O'	;Define o jogador 2 como O
	RET

JOGADOR_O:
	MOV BYTE PTR [JOGADOR1_CHAR], 'O'	;Define o jogador 1 como O
	MOV BYTE PTR [JOGADOR2_CHAR], 'X'	;Define o jogador 2 como X
	RET
SELECIONA_PRIMEIRO_JOGADOR ENDP




INICIALIZA_JOGO PROC
	LEA DI, BOARD_3X3
	LEA SI, BOARD_9X9
	LEA BX, JOGADOR1_NOME + 2
	MOV CX, 81
	MOV AL, 'L'

INICIALIZA_BOARD_LOOP:
	MOV [SI], AL
	INC SI
	LOOP INICIALIZA_BOARD_LOOP
	MOV CX, 9
	
INICIALIZA_BOARD_LOOP1:
	MOV [DI], AL
	INC DI
	LOOP INICIALIZA_BOARD_LOOP1
	MOV CX, 18
	MOV AL, '$'
	
INICIALIZA_JOGADOR1:
	MOV [BX], AL
	LOOP INICIALIZA_JOGADOR1
	LEA BX, JOGADOR2_NOME + 2
	MOV CX, 18
	
INICIALIZA_JOGADOR2:
	MOV [BX], AL
	LOOP INICIALIZA_JOGADOR2
	RET
INICIALIZA_JOGO ENDP




MOVER PROC										
	MOV AX, 0B800H						;Mete o ES a apontar para a 			
	MOV	ES, AX							;memoria de video
	MOV POS_X, 38						
	MOV POS_y, 12
	LEA SI, BOARD_9X9						;Carrega o endereço da BOARD_9X9 para SI
	
MOVER_CICLO:
	GOTO_XY	POS_X, POS_Y				;Vai para nova posição
	CALL READ_CHAR_CURSOR_POS
	MOV CHAR, AL						;Carrega CHAR com char na pos do cursor
	
LER_SETA:	
	CALL LE_TECLA						
	CMP	AH, 1
	JE CIMA								;Caso tecla pressionada salta para CIMA
	CMP AL, JOGADOR_CURR_CHAR
	JNE LER_SETA
	GOTO_XY	POS_X, POS_Y 				;Verifica se pode escrever char no ecra
	MOV	CL, CHAR						
	CMP	CL, 32							
	JNE LER_SETA						;So escreve se for espaço em branco
	CALL GET_CURSOR_POS
	CALL MAP9X9
	MOV	DL, AL							;Carrega DL com char
	CALL PRINT_CHAR
	JMP MOVER_FIM
	
CIMA:		
	CMP AL, 48H							;Se a tecla nao for seta para cima
	JNE	BAIXO							;Salta para BAIXO
	CMP DH, 7							;Se estiver em Y = 7, nao deixa subir
	JE LER_SETA
	DEC	POS_Y							;Sobe uma posicao
	JMP	MOVER_CICLO

BAIXO:
	CMP	AL, 50H							;Se a tecla nao for seta para baixo
	JNE	ESQUERDA                        ;Salta para ESQUERDA
	CMP DH, 17                          ;Se estiver em X = 17, nao deixa descer
	JE LER_SETA                         
	INC POS_Y			                ;Desce uma posicao
	JMP	MOVER_CICLO

ESQUERDA:
	CMP	AL, 4BH							;Se a tecla nao for seta para esquerda
	JNE	DIREITA                         ;Salta para DIREITA
	CMP DL, 26                          ;Se estiver em X = 26, nao deixa andar
	JE LER_SETA                         ;para a esquerda
	SUB POS_X, 3                        ;Anda 3 posicoes para a esquerda
	JMP	MOVER_CICLO

DIREITA:
	CMP	AL, 4DH							;Se a tecla nao for seta para direita
	JNE	LER_SETA                        ;Salta para LER_SETA
	CMP DL, 50                          ;Se estiver em X = 50, nao deixa andar
	JE LER_SETA                         ;para a direita
	ADD POS_X, 3                        ;Anda 3 posicoes para a direita
	JMP	MOVER_CICLO

MOVER_FIM:		
	RET
MOVER ENDP




MOVER_MENU PROC

CICLO_MENU:		
	GOTO_XY	POS_X,POS_Y					;Vai para nova posição
	
LER_SETA:	
	CALL LE_TECLA
	CMP	AH, 1
	JE CIMA_MENU
	CALL GET_CURSOR_POS	
	RET
	
CIMA_MENU:								
	CMP AL, 48H							;Se a tecla nao for seta para cima
	JNE	BAIXO_MENU                      ;Salta para BAIXO_MENU
	CMP DH, 18                          ;Se estiver em Y = 18, nao deixa subir
	JE CICLO_MENU                       
	DEC	POS_Y				            ;Sobe duas posicoes
	DEC POS_Y
	JMP	CICLO_MENU

BAIXO_MENU:		
	CMP	AL, 50H							;Se a tecla nao for seta para baixo
	JNE	CICLO_MENU                      ;Salta para CICLO_MENU
	CMP DH, 22                          ;Se estiver em Y = 22, nao deixa descer
	JE CICLO_MENU                       
	INC POS_Y		                    ;Desce duas posicoes
	INC POS_Y
	JMP	CICLO_MENU
MOVER_MENU ENDP




ATUALIZA_JOGADOR PROC
	MOV AL, JOGADOR_CURR_CHAR
	CMP AL, JOGADOR1_CHAR
	JNE ATUALIZA_JOGADOR2
	GOTO_XY 64, 3
	MOV DL, ' '
	CALL PRINT_CHAR
	GOTO_XY 64, 2
	MOV DL, '>'
	CALL PRINT_CHAR
	RET
	
ATUALIZA_JOGADOR2:
	GOTO_XY 64, 2
	MOV DL, ' '
	CALL PRINT_CHAR
	GOTO_XY 64, 3
	MOV DL, '>'
	CALL PRINT_CHAR
	RET
ATUALIZA_JOGADOR ENDP




MUDA_JOGADOR PROC
	CMP JOGADOR_CURR_CHAR, 'X'
	JE MUDA								;Se o char jogado era X, troca para O
	MOV JOGADOR_CURR_CHAR, 'X'				;Senao, passa a ser X
	JMP VOLTA
	
MUDA:
	MOV JOGADOR_CURR_CHAR, 'O'
	JMP VOLTA
	
VOLTA:
	RET
MUDA_JOGADOR ENDP




VERIFICA_VENCEDOR_3X3 PROC
	XOR BX, BX
	XOR CX, CX
	XOR DX, DX
	LEA DI, BOARD_3X3
	
VERIFICA_LINHA3X3:
	CMP CX, 3
	JE VERIFICA_COLUNA3X3
	CMP DX, 3
	JE GANHOU_BOARD3X3
	MOV AL, [DI]
	CMP AL, JOGADOR_CURR_CHAR
	JNE PROXIMA_LINHA3X3
	INC DI
	INC DX
	JMP VERIFICA_LINHA3X3
	
PROXIMA_LINHA3X3:
	XOR DX, DX
	LEA DI, BOARD_3X3
	INC CX
	ADD BX, 3
	ADD DI, BX
	JMP VERIFICA_LINHA3X3

VERIFICA_COLUNA3X3:
	XOR BX, BX
	XOR CX, CX
	XOR DX, DX
	LEA DI, BOARD_3X3
	
COLUNA_LOOP3X3:
	CMP CX, 3
	JE VERIFICA_DIAGONAL13X3
	CMP DX, 3
	JE GANHOU_BOARD3X3
	MOV AL, [DI]
	CMP AL, JOGADOR_CURR_CHAR
	JNE PROXIMA_COLUNA3X3
	ADD DI, 3
	INC DX
	JMP COLUNA_LOOP3X3

PROXIMA_COLUNA3X3:
	XOR DX, DX
	LEA DI, BOARD_3X3
	INC BX
	INC CX
	ADD DI, BX
	JMP COLUNA_LOOP3X3
	
VERIFICA_DIAGONAL13X3:
	XOR CX, CX
	LEA DI, BOARD_3X3

DIAGONAL1_LOOP3X3:
	CMP CX, 3
	JE GANHOU_BOARD3X3
	MOV AL, [DI]
	CMP AL, JOGADOR_CURR_CHAR
	JNE VERIFICA_DIAGONAL23X3
	ADD DI, 4
	INC CX
	JMP DIAGONAL1_LOOP3X3
	
VERIFICA_DIAGONAL23X3:
	XOR CX, CX
	LEA DI, BOARD_3X3
	ADD DI, 2
	
DIAGONAL2_LOOP3X3:
	CMP CX, 3
	JE GANHOU_BOARD3X3
	MOV AL, [DI]
	CMP AL, JOGADOR_CURR_CHAR
	JNE NAO_GANHOU_BOARD3X3
	ADD DI, 2
	INC CX
	JMP DIAGONAL2_LOOP3X3
	
NAO_GANHOU_BOARD3X3:
	MOV AL, 0
	RET
	
GANHOU_BOARD3X3:
	MOV AL, 1
	RET
VERIFICA_VENCEDOR_3X3 ENDP




VERIFICA_VENCEDOR_9X9 PROC
	XOR BX, BX
	XOR CX, CX
	XOR DX, DX
	LEA SI, BOARD_9X9
	ADD SI, BOARD_OFFSET_JOGADA
	LEA DI, BOARD_3X3
	
VERIFICA_LINHA9X9:
	CMP CX, 3
	JE VERIFICA_COLUNA9X9
	CMP DX, 3
	JE GANHOU_BOARD9X9
	MOV AL, [SI]
	CMP AL, JOGADOR_CURR_CHAR
	JNE PROXIMA_LINHA9X9
	INC SI
	INC DX
	JMP VERIFICA_LINHA9X9
	
PROXIMA_LINHA9X9:
	XOR DX, DX
	MOV SI, BOARD_OFFSET_JOGADA
	ADD BX, 9
	ADD SI, BX
	INC CX
	JMP VERIFICA_LINHA9X9

VERIFICA_COLUNA9X9:
	XOR BX, BX
	XOR CX, CX
	XOR DX, DX
	MOV SI, BOARD_OFFSET_JOGADA
	
COLUNA_LOOP9X9:
	CMP CX, 3
	JE VERIFICA_DIAGONAL19X9
	CMP DX, 3
	JE GANHOU_BOARD9X9
	MOV AL, [SI]
	CMP AL, JOGADOR_CURR_CHAR
	JNE PROXIMA_COLUNA9X9
	ADD SI, 9
	INC DX
	JMP COLUNA_LOOP9X9

PROXIMA_COLUNA9X9:
	XOR DX, DX
	MOV SI, BOARD_OFFSET_JOGADA
	INC BX
	ADD SI, BX
	INC CX
	JMP COLUNA_LOOP9X9
	
VERIFICA_DIAGONAL19X9:
	XOR CX, CX
	MOV SI, BOARD_OFFSET_JOGADA

DIAGONAL1_LOOP9X9:
	CMP CX, 3
	JE GANHOU_BOARD9X9
	MOV AL, [SI]
	CMP AL, JOGADOR_CURR_CHAR
	JNE VERIFICA_DIAGONAL29X9
	ADD SI, 10
	INC CX
	JMP DIAGONAL1_LOOP9X9
	
VERIFICA_DIAGONAL29X9:
	XOR CX, CX
	MOV SI, BOARD_OFFSET_JOGADA
	ADD SI, 2

DIAGONAL2_LOOP9X9:	
	CMP CX, 3
	JE GANHOU_BOARD9X9
	MOV AL, [SI]
	CMP AL, JOGADOR_CURR_CHAR
	JNE NAO_GANHOU_BOARD9X9
	ADD SI, 8
	INC CX
	JMP DIAGONAL2_LOOP9X9
	
NAO_GANHOU_BOARD9X9:
	RET

GANHOU_BOARD9X9:
	CALL PREENCHE_BOARD
	CALL MAP3X3
	RET
VERIFICA_VENCEDOR_9X9 ENDP




PREENCHE_BOARD PROC
	XOR BX, BX
	MOV CX, 3
	
PREENCHE_BOARD_LOOP:
	CMP BX, 3
	JE PREENCHE_BOARD_SAIR
	GOTO_XY IDX_CURR_X, IDX_CURR_Y
	MOV DL, JOGADOR_CURR_CHAR
	CALL PRINT_CHAR
	ADD IDX_CURR_X, 3
	LOOP PREENCHE_BOARD_LOOP
	MOV CX, 3
	INC BX
	INC IDX_CURR_Y
	SUB IDX_CURR_X, 9
	JMP PREENCHE_BOARD_LOOP

PREENCHE_BOARD_SAIR:
	RET
PREENCHE_BOARD ENDP




MAP3X3 PROC
	CMP BOARD_OFFSET_JOGADA, 0
	JE Q1_3X3
	CMP BOARD_OFFSET_JOGADA, 3
	JE Q2_3X3
	CMP BOARD_OFFSET_JOGADA, 6
	JE Q3_3X3
	CMP BOARD_OFFSET_JOGADA, 27
	JE Q4_3X3
	CMP BOARD_OFFSET_JOGADA, 30
	JE Q5_3X3
	CMP BOARD_OFFSET_JOGADA, 33
	JE Q6_3X3
	CMP BOARD_OFFSET_JOGADA, 54
	JE Q7_3X3
	CMP BOARD_OFFSET_JOGADA, 57
	JE Q8_3X3
	CMP BOARD_OFFSET_JOGADA, 60
	JE Q9_3X3

Q1_3X3:
	GOTO_XY 64, 11
	MOV DL, JOGADOR_CURR_CHAR
	CALL PRINT_CHAR
	MOV AL, JOGADOR_CURR_CHAR
	MOV [DI], AL
	JMP MAP_FIM_3X3
	
Q2_3X3:
	GOTO_XY 67, 11
	MOV DL, JOGADOR_CURR_CHAR
	CALL PRINT_CHAR
	ADD DI, 1
	MOV AL, JOGADOR_CURR_CHAR
	MOV [DI], AL
	JMP MAP_FIM_3X3
	
Q3_3X3:
	GOTO_XY 70, 11
	MOV DL, JOGADOR_CURR_CHAR
	CALL PRINT_CHAR
	ADD DI, 2
	MOV AL, JOGADOR_CURR_CHAR
	MOV [DI], AL
	JMP MAP_FIM_3X3
	
Q4_3X3:
	GOTO_XY 64, 12
	MOV DL, JOGADOR_CURR_CHAR
	CALL PRINT_CHAR
	ADD DI, 3
	MOV AL, JOGADOR_CURR_CHAR
	MOV [DI], AL
	JMP MAP_FIM_3X3
	
Q5_3X3:
	GOTO_XY 67, 12
	MOV DL, JOGADOR_CURR_CHAR
	CALL PRINT_CHAR
	ADD DI, 4
	MOV AL, JOGADOR_CURR_CHAR
	MOV [DI], AL
	JMP MAP_FIM_3X3

Q6_3X3:
	GOTO_XY 70, 12
	MOV DL, JOGADOR_CURR_CHAR
	CALL PRINT_CHAR
	ADD DI, 5
	MOV AL, JOGADOR_CURR_CHAR
	MOV [DI], AL
	JMP MAP_FIM_3X3
	
Q7_3X3:
	GOTO_XY 64, 13
	MOV DL, JOGADOR_CURR_CHAR
	CALL PRINT_CHAR
	ADD DI, 6
	MOV AL, JOGADOR_CURR_CHAR
	MOV [DI], AL
	JMP MAP_FIM_3X3
	
Q8_3X3:
	GOTO_XY 67, 13
	MOV DL, JOGADOR_CURR_CHAR
	CALL PRINT_CHAR
	ADD DI, 7
	MOV AL, JOGADOR_CURR_CHAR
	MOV [DI], AL
	JMP MAP_FIM_3X3
	
Q9_3X3:
	GOTO_XY 70, 13
	MOV DL, JOGADOR_CURR_CHAR
	CALL PRINT_CHAR
	ADD DI, 8
	MOV AL, JOGADOR_CURR_CHAR
	MOV [DI], AL
	JMP MAP_FIM_3X3

MAP_FIM_3X3:
	RET
MAP3X3 ENDP




MAP9X9 PROC
	MOV AL, JOGADOR_CURR_CHAR
	CMP DH, 7							;Procura a LINHA_9X9 onde o char foi
	JE L1_9X9							;introduzido e adiciona o offset
	CMP DH, 8							;necessario
	JE L2_9X9							;Fica mapeado na array por linhas,
	CMP DH, 9							;o que pode nao ser a opcao mais
	JE L3_9X9							;pratica para calculos, mas simplifica
	CMP DH, 11							;o mapeamento
	JE L4_9X9
	CMP DH, 12
	JE L5_9X9
	CMP DH, 13
	JE L6_9X9
	CMP DH, 15
	JE L7_9X9
	CMP DH, 16
	JE L8_9X9
	CMP DH, 17
	JE L9_9X9

L1_9X9:
	MOV BH, 7
	MOV BOARD_OFFSET_JOGADA, 0
	JMP LINHA_9X9

L2_9X9:
	MOV BH, 7
	MOV BOARD_OFFSET_JOGADA, 0
	ADD SI, 9
	JMP LINHA_9X9

L3_9X9:
	MOV BH, 7
	MOV BOARD_OFFSET_JOGADA, 0
	ADD SI, 18
	JMP LINHA_9X9

L4_9X9:
	MOV BH, 11
	MOV BOARD_OFFSET_JOGADA, 27
	ADD SI, 27
	JMP LINHA_9X9
	
L5_9X9:
	MOV BH, 11
	MOV BOARD_OFFSET_JOGADA, 27
	ADD SI, 36
	JMP LINHA_9X9

L6_9X9:
	MOV BH, 11
	MOV BOARD_OFFSET_JOGADA, 27
	ADD SI, 45
	JMP LINHA_9X9

L7_9X9:
	MOV BH, 15
	MOV BOARD_OFFSET_JOGADA, 54
	ADD SI, 54
	JMP LINHA_9X9
	
L8_9X9:
	MOV BH, 15
	MOV BOARD_OFFSET_JOGADA, 54
	ADD SI, 63
	JMP LINHA_9X9
	
L9_9X9:
	MOV BH, 15
	MOV BOARD_OFFSET_JOGADA, 54
	ADD SI, 72
	JMP LINHA_9X9
	
LINHA_9X9:
	CMP DL, 26
	JE Q1_9X9
	CMP DL, 29
	JE Q2_9X9
	CMP DL, 32
	JE Q3_9X9
	CMP DL, 35
	JE Q4_9X9
	CMP DL, 38
	JE Q5_9X9
	CMP DL, 41
	JE Q6_9X9
	CMP DL, 44
	JE Q7_9X9
	CMP DL, 47	
	JE Q8_9X9
	CMP DL, 50
	JE Q9_9X9
	
Q1_9X9:
	MOV BL, 26
	MOV [SI], AL
	JMP MAP_FIM_9X9
	
Q2_9X9:
	MOV BL, 26
	ADD SI, 1
	MOV [SI], AL
	JMP MAP_FIM_9X9
	
Q3_9X9:
	MOV BL, 26
	ADD SI, 2
	MOV [SI], AL
	JMP MAP_FIM_9X9
	
Q4_9X9:
	MOV BL, 35
	ADD BOARD_OFFSET_JOGADA, 3
	ADD SI, 3
	MOV [SI], AL
	JMP MAP_FIM_9X9
	
Q5_9X9:
	MOV BL, 35
	ADD BOARD_OFFSET_JOGADA, 3
	ADD SI, 4
	MOV [SI], AL
	JMP MAP_FIM_9X9
	
Q6_9X9:
	MOV BL, 35
	ADD BOARD_OFFSET_JOGADA, 3
	ADD SI, 5
	MOV [SI], AL
	JMP MAP_FIM_9X9
	
Q7_9X9:
	MOV BL, 44
	ADD BOARD_OFFSET_JOGADA, 6
	ADD SI, 6
	MOV [SI], AL
	JMP MAP_FIM_9X9
	
Q8_9X9:
	MOV BL, 44
	ADD BOARD_OFFSET_JOGADA, 6
	ADD SI, 7
	MOV [SI], AL
	JMP MAP_FIM_9X9
	
Q9_9X9:
	MOV BL, 44
	ADD BOARD_OFFSET_JOGADA, 6
	ADD SI, 8
	MOV [SI], AL
	JMP MAP_FIM_9X9
	
MAP_FIM_9X9:
	MOV IDX_CURR_X, BL
	MOV IDX_CURR_Y, BH
	RET
MAP9X9 ENDP




APAGA_ECRAN	PROC
	MOV	AX, 0B800H						;Mete o ES a apontar para
	MOV ES, AX							;a memoria de video
	XOR BX, BX							;Limpa o BX
	MOV	CX, 25*80						;Calcula tamanho da tela

APAGA:	
	MOV	BYTE PTR ES:[BX], ' '			;Escreve um espaço em branco no ES
	MOV	BYTE PTR ES:[BX + 1], 7			;Define a cor do espaço em branco
	INC	BX								;Aponta para a proxima posicao na 
	INC BX								;memoria de video
	LOOP APAGA
	RET
APAGA_ECRAN	ENDP
	
	


PRINT_FICHEIRO PROC
    XOR AL, AL
    CALL OPEN_FILE
    JC ERRO_ABRIR
    MOV HANDLE_FICH, AX
    JMP LER_CICLO

ERRO_ABRIR:
    LEA DX, ERRO_OPEN
    CALL PRINT_STRING
    JMP SAI_F

LER_CICLO:
    MOV BX, HANDLE_FICH
    MOV CX, 1
    LEA DX, CAR_FICH
    CALL READ_FILE
	JC ERRO_LER
	CMP AX, 0		;EOF?
	JE FECHA_FICHEIRO
	MOV DL, CAR_FICH
	CALL PRINT_CHAR
	JMP	LER_CICLO

ERRO_LER:
    LEA DX, ERRO_LER_MSG
    CALL PRINT_STRING

FECHA_FICHEIRO:
    MOV BX, HANDLE_FICH
    CALL CLOSE_FILE
    JNC SAI_F
    LEA DX, ERRO_CLOSE
    CALL PRINT_STRING

SAI_F:	
	RET
PRINT_FICHEIRO ENDP		




LE_TECLA PROC
	CALL GET_CHAR
	XOR AH, AH
	CMP	AL, 0
	JNE	SAI_TECLA
	CALL GET_CHAR
	MOV	AH, 1
	
SAI_TECLA:	
	RET
LE_TECLA ENDP



;////////////////////HELPER PROCS////////////////////;

;CARREGAR DX COM O ENDEREÇO DA STRING
PRINT_STRING PROC
	MOV AH, 09H
	INT 21H
	RET
PRINT_STRING ENDP

;CARREGAR DL COM O CARACTER
PRINT_CHAR PROC
	MOV AH, 02H
	INT 21H
	RET
PRINT_CHAR ENDP

;CARREGAR DX COM O BUFFER, RETORNA BUFFER COM A STRING
GET_STRING PROC
	MOV AH, 0AH
	INT 21H
	RET
GET_STRING ENDP

;METE O CARACTER LIDO EM AL
GET_CHAR PROC
	MOV AH, 08H
	INT 21H
	RET
GET_CHAR ENDP

OPEN_FILE PROC
	MOV AH, 3DH
	INT 21H
	RET
OPEN_FILE ENDP

READ_FILE PROC
	MOV AH, 3FH 
	INT 21H
	RET
READ_FILE ENDP

CLOSE_FILE PROC
	MOV AH, 3EH
	INT 21H
	RET
CLOSE_FILE ENDP

READ_SYSTEM_TIMER PROC
	MOV AH, 0
	INT 1AH
	RET
READ_SYSTEM_TIMER ENDP

;RETORNA CARACTER LIDO EM AL E A COR EM AH
READ_CHAR_CURSOR_POS PROC
	MOV AH, 08H
	MOV BH, 0
	INT 10H
	RET
READ_CHAR_CURSOR_POS ENDP

;RETORNA DH COM LINHA_9X9 E DL COM COLUNA
GET_CURSOR_POS PROC
	MOV AH, 03H
	MOV BH, 0
	INT 10H
	RET
GET_CURSOR_POS ENDP

;CARREGAR DH COM LINHA_9X9 E DL COM COLUNA
SET_CURSOR_POS PROC
	MOV AH, 02H
	MOV BH, 0
	INT 10H
	RET
SET_CURSOR_POS ENDP

SET_BACKGROUND_COLOR PROC
	MOV AH, 0BH
	MOV BH, 0
	INT 10H
	RET
SET_BACKGROUND_COLOR ENDP


EXIT PROC
	MOV AH, 4CH
	INT 21H
	RET
EXIT ENDP

CODIGO ENDS
END MAIN